/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.sisong.view;

import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import ucr.ac.cr.sisong.model.Song;

/**
 *
 * @author lara3
 */
public class DataPanelSong extends javax.swing.JPanel {

    /**
     * Creates new form DataPanelSong
     */
    public DataPanelSong() {
        initComponents();
    }
    public void setLbIdSong(int idSong){
        this.lbIDSong.setText(String.valueOf(idSong));
    }//Cargar el id en el label 
    public Song getSong()
    {
        return new Song(this.txtTittle.getText(),this.cbMusicGenre.getSelectedItem().toString(),Integer.parseInt(this.lbIDSong.getText()),Integer.parseInt(this.spRelaseYear.getValue().toString()),Double.parseDouble(this.spTime.getValue().toString()));
        
    }
    public void setSong(Song song)
    {
        this.lbIDSong.setText(String.valueOf(song.getIdSong()));
        this.txtTittle.setText(song.getTitle());
        this.spTime.setValue(song.getTime());
        this.spRelaseYear.setValue(song.getRealseYear());
        this.cbMusicGenre.setSelectedItem(song.getMusicGenre());
    }
    public void clean()
    {
        this.lbIDSong.setText("");
        this.txtTittle.setText("");
        this.spTime.setValue(0);
        this.spRelaseYear.setValue(2024);
        this.cbMusicGenre.setSelectedIndex(0);
    }
    public void setCbSong(String[] idSong){
        DefaultComboBoxModel model = new DefaultComboBoxModel(idSong);
        model.insertElementAt("Selected option", 0);
        this.cbSong.setModel(model);
    }
    public void listenCombo(ActionListener controller){
        this.cbSong.addActionListener(controller);
    }
    public String getCbSong(){
        return this.cbSong.getSelectedItem().toString();
    }
    public void setEditCbCombo(boolean state){
        this.cbSong.setEnabled(state);
    }
    public void addGenre(){
        this.cbMusicGenre.setModel(new DefaultComboBoxModel<>(new String[]{"Select genre", "Musica clasica", "Jazz", "Salsa", "LoFi", "Rock", "Metal", "Cumbia", "Bolero", "Reggae", "Merengue", "Electronica", "Dustep"}));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbIDSong = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTittle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        spTime = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        cbMusicGenre = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        spRelaseYear = new javax.swing.JSpinner();
        cbSong = new javax.swing.JComboBox<>();

        jLabel8.setBackground(new java.awt.Color(0, 153, 153));
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 51));
        jLabel1.setText("Song record");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Id Song ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        lbIDSong.setForeground(new java.awt.Color(255, 255, 0));
        add(lbIDSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 80, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Tittle");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        add(txtTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 97, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Duration");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        spTime.setModel(new javax.swing.SpinnerNumberModel(0.1d, 0.1d, null, 0.1d));
        add(spTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 97, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Genre");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        cbMusicGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbMusicGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 101, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("Release Year");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        spRelaseYear.setModel(new javax.swing.SpinnerNumberModel(2024, 1582, 2024, 1));
        add(spRelaseYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 101, -1));

        cbSong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empty record", "Musica clasica", "Jazz", "Salsa", "LoFi", "Rock", "Metal", "Cumbia", "Bolero", "Reggae", "Merengue", "Electronica", "Dustep", " " }));
        cbSong.setActionCommand("cbSong");
        cbSong.setEnabled(false);
        cbSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSongActionPerformed(evt);
            }
        });
        add(cbSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cbSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbMusicGenre;
    private javax.swing.JComboBox<String> cbSong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbIDSong;
    private javax.swing.JSpinner spRelaseYear;
    private javax.swing.JSpinner spTime;
    private javax.swing.JTextField txtTittle;
    // End of variables declaration//GEN-END:variables

    public void setSong(Song song, double parseDouble) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
